// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/halalala222/gf-learning/internal/logic/ncu_home"
	_ "github.com/halalala222/gf-learning/internal/logic/user"
	_ "github.com/halalala222/gf-learning/internal/logic/wallet"
)
