// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// NcuHome is the golang structure of table ncu_home for DAO operations like Where/Data.
type NcuHome struct {
	g.Meta `orm:"table:ncu_home, do:true"`
	Name   interface{} //
	Sex    interface{} //
	Group  interface{} //
	Id     interface{} //
}
