// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Participant is the golang structure of table participant for DAO operations like Where/Data.
type Participant struct {
	g.Meta    `orm:"table:participant, do:true"`
	Id        interface{} //
	StuId     interface{} //
	Qq        interface{} //
	Name      interface{} //
	Question  interface{} //
	Puid      interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	IsCheckIn interface{} //
}
