// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Students is the golang structure of table students for DAO operations like Where/Data.
type Students struct {
	g.Meta    `orm:"table:students, do:true"`
	Id        interface{} //
	StudentId interface{} //
	Name      interface{} //
	Age       interface{} //
	Class     interface{} //
	Major     interface{} //
	College   interface{} //
}
