// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ParticipantDao is the data access object for table participant.
type ParticipantDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns ParticipantColumns // columns contains all the column names of Table for convenient usage.
}

// ParticipantColumns defines and stores column names for table participant.
type ParticipantColumns struct {
	Id        string //
	StuId     string //
	Qq        string //
	Name      string //
	Question  string //
	Puid      string //
	CreatedAt string //
	UpdatedAt string //
	IsCheckIn string //
}

// participantColumns holds the columns for table participant.
var participantColumns = ParticipantColumns{
	Id:        "id",
	StuId:     "stu_id",
	Qq:        "qq",
	Name:      "name",
	Question:  "question",
	Puid:      "puid",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	IsCheckIn: "is_check_in",
}

// NewParticipantDao creates and returns a new DAO object for table data access.
func NewParticipantDao() *ParticipantDao {
	return &ParticipantDao{
		group:   "default",
		table:   "participant",
		columns: participantColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ParticipantDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ParticipantDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ParticipantDao) Columns() ParticipantColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ParticipantDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ParticipantDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ParticipantDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
