// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"github.com/halalala222/gf-learning/internal/dao/internal"
	"github.com/halalala222/gf-learning/internal/model/do"
)

// internalNcuHomeDao is internal type for wrapping internal DAO implements.
type internalNcuHomeDao = *internal.NcuHomeDao

// ncuHomeDao is the data access object for table ncu_home.
// You can define custom methods on it to extend its functionality as you wish.
type ncuHomeDao struct {
	internalNcuHomeDao
}

var (
	// NcuHome is globally public accessible object for table ncu_home operations.
	NcuHome = ncuHomeDao{
		internal.NewNcuHomeDao(),
	}
)

// Fill with you ideas below.

func (n ncuHomeDao) CreateNcuHome(ctx context.Context, ncuHome *do.NcuHome) (int64, error) {
	result, err := NcuHome.Ctx(ctx).Data(ncuHome).Insert()
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
