// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/halalala222/gf-learning/internal/dao/internal"
)

// internalParticipantDao is internal type for wrapping internal DAO implements.
type internalParticipantDao = *internal.ParticipantDao

// participantDao is the data access object for table participant.
// You can define custom methods on it to extend its functionality as you wish.
type participantDao struct {
	internalParticipantDao
}

var (
	// Participant is globally public accessible object for table participant operations.
	Participant = participantDao{
		internal.NewParticipantDao(),
	}
)

// Fill with you ideas below.
