// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// NcuHome is the golang structure for table ncu_home.
type NcuHome struct {
	Name  string `json:"name"  ` //
	Sex   string `json:"sex"   ` //
	Group string `json:"group" ` //
	Id    int    `json:"id"    ` //
}
