// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Students is the golang structure for table students.
type Students struct {
	Id        int    `json:"id"        ` //
	StudentId string `json:"studentId" ` //
	Name      string `json:"name"      ` //
	Age       int    `json:"age"       ` //
	Class     string `json:"class"     ` //
	Major     string `json:"major"     ` //
	College   string `json:"college"   ` //
}
